-- Movement series (recurring + installments) and applied-balance semantics.

-- ---------------------------------------------------------------------------
-- movement_series
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.movement_series (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL DEFAULT auth.uid(),
  kind text NOT NULL CHECK (kind IN ('recurring', 'installment')),
  frequency text NOT NULL CHECK (frequency IN ('weekly', 'biweekly', 'monthly', 'yearly')),
  amount numeric NOT NULL,
  total_amount numeric,
  installment_count integer,
  description text NOT NULL,
  category bigint NOT NULL REFERENCES public.category (id),
  "from" bigint NOT NULL REFERENCES public.account (id),
  start_date date NOT NULL,
  end_date date,
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'completed')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz,
  CONSTRAINT movement_series_installment_fields_check CHECK (
    (kind = 'installment' AND total_amount IS NOT NULL AND installment_count IS NOT NULL AND installment_count >= 2)
    OR (kind = 'recurring' AND total_amount IS NULL AND installment_count IS NULL)
  )
);

CREATE INDEX IF NOT EXISTS movement_series_user_id_idx
  ON public.movement_series (user_id);

CREATE INDEX IF NOT EXISTS movement_series_status_idx
  ON public.movement_series (status)
  WHERE status = 'active';

ALTER TABLE public.movement_series ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "movement_series_select_own" ON public.movement_series;
DROP POLICY IF EXISTS "movement_series_insert_own" ON public.movement_series;
DROP POLICY IF EXISTS "movement_series_update_own" ON public.movement_series;
DROP POLICY IF EXISTS "movement_series_delete_own" ON public.movement_series;

CREATE POLICY "movement_series_select_own"
  ON public.movement_series
  FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "movement_series_insert_own"
  ON public.movement_series
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "movement_series_update_own"
  ON public.movement_series
  FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "movement_series_delete_own"
  ON public.movement_series
  FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- movement: applied backfill + series link
-- ---------------------------------------------------------------------------
UPDATE public.movement
SET applied = true
WHERE applied IS DISTINCT FROM true;

ALTER TABLE public.movement
  ALTER COLUMN applied SET DEFAULT true,
  ALTER COLUMN applied SET NOT NULL;

ALTER TABLE public.movement
  ADD COLUMN IF NOT EXISTS series_id bigint REFERENCES public.movement_series (id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS installment_index integer;

CREATE INDEX IF NOT EXISTS movement_unapplied_done_at_idx
  ON public.movement (done_at)
  WHERE applied = false;

CREATE INDEX IF NOT EXISTS movement_series_id_idx
  ON public.movement (series_id)
  WHERE series_id IS NOT NULL;
