import {
  BusFront,
  CirclePercent,
  Clapperboard,
  Coins,
  Dumbbell,
  File,
  FileText,
  Forward,
  Hamburger,
  HandCoins,
  Hospital,
  House,
  Laptop,
  Martini,
  MessageCircleQuestion,
  PawPrint,
  PiggyBank,
  PlaneTakeoff,
  ReceiptText,
  School,
  Shirt,
  ShoppingCart,
  Smartphone,
  TvMinimal,
  Wallet,
} from "lucide-react";
import { CategoryIcons } from "../types/global.types";

export const CATEGORY_ICONS: CategoryIcons = {
  food: Hamburger,
  commissions: ReceiptText,
  services: File,
  education: School,
  technology: Laptop,
  entertainment: Clapperboard,
  home: House,
  taxes: FileText,
  clothing: Shirt,
  pets: PawPrint,
  other: MessageCircleQuestion,
  loans: HandCoins,
  healthcare: Hospital,
  party: Martini,
  market: ShoppingCart,
  subscription: TvMinimal,
  transport: BusFront,
  travels: PlaneTakeoff,
  telephone: Smartphone,
  salary: Wallet,
  awards: Coins,
  investments: PiggyBank,
  sales: CirclePercent,
  transfer: Forward,
  sports: Dumbbell,
} as const;

export const categoryColorsLiterals = [
  "amber",
  "blue",
  "cyan",
  "fuchsia",
  "gray",
  "green",
  "indigo",
  "orange",
  "pink",
  "red",
  "rose",
  "sky",
  "teal",
  "violet",
  "yellow",
] as const;
