import { CategoryIcons } from "@/types/general";
import {
  mdiFoodOutline,
  mdiReceiptOutline,
  mdiFileOutline,
  mdiSchoolOutline,
  mdiLaptop,
  mdiMovieOpenPlayOutline,
  mdiHomeOutline,
  mdiFileAlertOutline,
  mdiHanger,
  mdiAppleKeyboardCommand,
  mdiHandCoinOutline,
  mdiHospital,
  mdiGlassCocktail,
  mdiCartOutline,
  mdiTelevision,
  mdiAirplane,
  mdiBus,
  mdiCellphone,
  mdiPaw,
  mdiCash,
  mdiPiggyBankOutline,
  mdiWallet,
  mdiSale,
  mdiTransfer,
  mdiDumbbell,
} from "@mdi/js";

export const CATEGORY_ICONS: CategoryIcons = {
  food: mdiFoodOutline,
  comissions: mdiReceiptOutline,
  services: mdiFileOutline,
  education: mdiSchoolOutline,
  technology: mdiLaptop,
  entertainment: mdiMovieOpenPlayOutline,
  home: mdiHomeOutline,
  taxes: mdiFileAlertOutline,
  clothing: mdiHanger,
  pets: mdiPaw,
  other: mdiAppleKeyboardCommand,
  loans: mdiHandCoinOutline,
  healthcare: mdiHospital,
  party: mdiGlassCocktail,
  market: mdiCartOutline,
  subscription: mdiTelevision,
  transport: mdiBus,
  travels: mdiAirplane,
  telephone: mdiCellphone,
  salary: mdiWallet,
  awards: mdiCash,
  investments: mdiPiggyBankOutline,
  sales: mdiSale,
  transfer: mdiTransfer,
  sports: mdiDumbbell,
};

export const MONTHS = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];
