import { CategoryIcons } from "@/types/general";
import {
  BusFront,
  CirclePercent,
  Clapperboard,
  Coins,
  Dumbbell,
  File,
  FileText,
  Forward,
  Hamburger,
  HandCoins,
  Hospital,
  House,
  Laptop,
  Martini,
  MessageCircleQuestion,
  PawPrint,
  PiggyBank,
  PlaneTakeoff,
  ReceiptText,
  School,
  Shirt,
  ShoppingCart,
  Smartphone,
  TvMinimal,
  Wallet,
} from "lucide-react";

export const CATEGORY_ICONS: CategoryIcons = {
  food: Hamburger,
  comissions: ReceiptText,
  services: File,
  education: School,
  technology: Laptop,
  entertainment: Clapperboard,
  home: House,
  taxes: FileText,
  clothing: Shirt,
  pets: PawPrint,
  other: MessageCircleQuestion,
  loans: HandCoins,
  healthcare: Hospital,
  party: Martini,
  market: ShoppingCart,
  subscription: TvMinimal,
  transport: BusFront,
  travels: PlaneTakeoff,
  telephone: Smartphone,
  salary: Wallet,
  awards: Coins,
  investments: PiggyBank,
  sales: CirclePercent,
  transfer: Forward,
  sports: Dumbbell,
};

export const MONTHS = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];
