import {
  mdiFoodOutline,
  mdiReceiptOutline,
  mdiFileOutline,
  mdiSchoolOutline,
  mdiLaptop,
  mdiMovieOpenPlayOutline,
  mdiHomeOutline,
  mdiFileAlertOutline,
  mdiHanger,
  mdiChartLine,
  mdiAppleKeyboardCommand,
  mdiHandCoinOutline,
  mdiHospital,
  mdiShoppingOutline,
  mdiCartOutline,
  mdiTelevision,
  mdiAirplane,
  mdiBus,
  mdiCellphone,
  mdiPaw,
  mdiCash,
  mdiPiggyBankOutline,
  mdiWallet,
  mdiSale,
} from "@mdi/js";

export const CATEGORY_ICONS = {
  food: mdiFoodOutline,
  comissions: mdiReceiptOutline,
  services: mdiFileOutline,
  education: mdiSchoolOutline,
  technology: mdiLaptop,
  entertainment: mdiMovieOpenPlayOutline,
  home: mdiHomeOutline,
  taxes: mdiFileAlertOutline,
  clothing: mdiHanger,
  pets: mdiPaw,
  investments: mdiChartLine,
  other: mdiAppleKeyboardCommand,
  loans: mdiHandCoinOutline,
  healthcare: mdiHospital,
  shopping: mdiShoppingOutline,
  market: mdiCartOutline,
  subscription: mdiTelevision,
  transport: mdiBus,
  travels: mdiAirplane,
  telephone: mdiCellphone,
  salary: mdiWallet,
  awards: mdiCash,
  investments: mdiPiggyBankOutline,
  sales: mdiSale,
};
